# Generated by Django 4.0.1 on 2022-01-18 19:32

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('fecha', models.DateField(blank=True, verbose_name='Fecha')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('rango', models.PositiveIntegerField(blank=True, verbose_name='Rango')),
                ('director', models.CharField(max_length=100, verbose_name='Director')),
                ('autores', models.CharField(max_length=120, verbose_name='Autores')),
                ('duracion', models.CharField(max_length=100, verbose_name='Duracion')),
                ('imagen', models.CharField(max_length=100, verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Pelicula',
                'verbose_name_plural': 'Peliculas',
            },
        ),
    ]
