# Generated by Django 4.0.1 on 2022-01-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='autores',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Autores'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='director',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Director'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='duracion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Duracion'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='imagen',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='nombre',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='rango',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Rango'),
        ),
    ]
