# Generated by Django 4.0.1 on 2022-01-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_user_edad_alter_user_email_alter_user_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='password'),
        ),
    ]
