# Generated by Django 4.0.1 on 2022-01-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(blank=True, null=True, verbose_name='password'),
        ),
    ]
